### PR TITLE
fix: first link nav issue

### LINKED ISSUE #6: Fix - first nav link always selected
When navigating along the navigation links, it seems that the first navigation link is always selected. Looking for clean ways to remove the first link being selected when other links are selected.

### PR DESCRIPTION
**Pull request by vim-usds**
- update tests
- closes #6

### CODE REVIEW

File: src/components/AppHeader/AppHeader.tsx [hunk 1]
```diff
@@ -73,7 +74,16 @@ const AppHeader = () => {
     <LocalizedLink
```
Comment (mattbowen-usds) [inline src/components/AppHeader/AppHeader.tsx:74]: Since you have some data structure of nav links above, do you think instead of repeating the localized links, it would makes sense to iterate over the stuff in NAV_LINKS_COPY? Like you could make a slightly richer data structure that contains both the copy and the pathname for each link and generated both NAV_LINKS_COPY and these from it. That way you don't repeat my mistake of hardcoding everything and having a pain to update it, only to later find a much simpler way to set things up

File: src/components/AppHeader/AppHeader.tsx [hunk 2]
```diff
@@ -27,7 +28,7 @@ import { PAGES_ENDPOINTS } from '@/data/constants';
  * @param {Location} location
  * @return {JSX.Element}
  */
-const AppHeader = () => {
+const AppHeader = ({ location }: ILocation) => {
```
Comment (mattbowen-usds) [inline src/components/AppHeader/AppHeader.tsx:31]: I ended up passing location in via `gatsby-node.ts`, but i'm curious how these pages know their location --- it felt like something that should be just like, available globally, but then I didn't find any promising place so i just passed it via context.

**Review by mattbowen-usds — COMMENTED** [review]
Added a question about a refactor that I would suggest. If you feel strongly that you don't want to do that now, I can switch to approved.

File: src/components/AppHeader/AppHeader.tsx (hunk 1 above)
Comment (vim-usds) [reply src/components/AppHeader/AppHeader.tsx:74]: This is awesome feedback @mattbowen-usds! Thank you so much! I totally agree!

File: src/components/AppHeader/AppHeader.tsx (hunk 2 above)
Comment (vim-usds) [reply src/components/AppHeader/AppHeader.tsx:31]: yeah I agree, I'll have to look at how you did this, it would be better to not have to declare it on every page. THANKS!

**Review by mattbowen-usds — APPROVED** [review]
Nicely done!
